### ISSUE TITLE
AssertionError: missing pagination params

### ISSUE THREAD

**Issue by dor1202** [uriyyo/fastapi-pagination#1028]
Hi, love the lib!!
I'm upgrading the dependencies versions in my repo to use python 3.12 and getting this error:
```
/Users/.../Library/Caches/pypoetry/virtualenvs/sample-service-n-Or4Wts-py3.12/bin/python -m uvicorn sample_service.main:app --reload --host=0.0.0.0 --port=10020
INFO:     Will watch for changes in these directories: ['/Users/.../Software/GitLab/sample-service']
INFO:     Uvicorn running on http://0.0.0.0:10020 (Press CTRL+C to quit)
INFO:     Started reloader process [45664] using WatchFiles
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/Users/.../.pyenv/versions/3.12.1/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/.../.pyenv/versions/3.12.1/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/sample-service-n-Or4Wts-py3.12/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/sample-service-n-Or4Wts-py3.12/lib/python3.12/site-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../.pyenv/versions/3.12.1/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/.../.pyenv/versions/3.12.1/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/sample-service-n-Or4Wts-py3.12/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    config.load()
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/sample-service-n-Or4Wts-py3.12/lib/python3.12/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/sample-service-n-Or4Wts-py3.12/lib/python3.12/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../.pyenv/versions/3.12.1/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/.../Software/GitLab/sample-service/sample_service/main.py", line 41, in <module>
    app = get_application()
          ^^^^^^^^^^^^^^^^^
  File "/Users/.../Software/GitLab/sample-service/sample_service/main.py", line 37, in get_application
    add_pagination(application)
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/sample-service-n-Or4Wts-py3.12/lib/python3.12/site-packages/fastapi_pagination/api.py", line 366, in add_pagination
    _add_pagination(parent)
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/sample-service-n-Or4Wts-py3.12/lib/python3.12/site-packages/fastapi_pagination/api.py", line 362, in _add_pagination
    _update_route(route)
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/sample-service-n-Or4Wts-py3.12/lib/python3.12/site-packages/fastapi_pagination/api.py", line 345, in _update_route
    get_parameterless_sub_dependant(
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/sample-service-n-Or4Wts-py3.12/lib/python3.12/site-packages/fastapi/dependencies/utils.py", line 124, in get_parameterless_sub_dependant
    return get_sub_dependant(depends=depends, dependency=depends.dependency, path=path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/sample-service-n-Or4Wts-py3.12/lib/python3.12/site-packages/fastapi/dependencies/utils.py", line 147, in get_sub_dependant
    sub_dependant = get_dependant(
                    ^^^^^^^^^^^^^^
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/sample-service-n-Or4Wts-py3.12/lib/python3.12/site-packages/fastapi/dependencies/utils.py", line 268, in get_dependant
    sub_dependant = get_param_sub_dependant(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/sample-service-n-Or4Wts-py3.12/lib/python3.12/site-packages/fastapi/dependencies/utils.py", line 111, in get_param_sub_dependant
    return get_sub_dependant(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/sample-service-n-Or4Wts-py3.12/lib/python3.12/site-packages/fastapi/dependencies/utils.py", line 147, in get_sub_dependant
    sub_dependant = get_dependant(
                    ^^^^^^^^^^^^^^
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/sample-service-n-Or4Wts-py3.12/lib/python3.12/site-packages/fastapi/dependencies/utils.py", line 289, in get_dependant
    add_param_to_fields(field=param_field, dependant=dependant)
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/sample-service-n-Or4Wts-py3.12/lib/python3.12/site-packages/fastapi/dependencies/utils.py", line 483, in add_param_to_fields
    assert (
AssertionError: non-body parameters must be in path, query, header or cookie: size
```

Versions:
```
[tool.poetry.dependencies]
python = "^3.12"
fastapi = { version = "^0.109.2", extras = ["all"] }
pydantic = "^2.6.1"
fastapi-pagination = "^0.12.15"
uvicorn = "^0.27.0"
```

It worked fine in with the versions I used before:
```
[tool.poetry.dependencies]
python = "^3.10"
fastapi = { version = "^0.95.1", extras = ["all"] }
pydantic = "^1.10.2"
fastapi-pagination = "^0.11.1"
uvicorn = "^0.22.0"
```

Any ideas what could be the issue?

**Comment by uriyyo** [comment]
Hi @dor1202,

Your issue might be similar to what other users had - https://github.com/uriyyo/fastapi-pagination/issues/926#issuecomment-1870015711

Are you using `Page.with_custom_options` method?

**Comment by dor1202** [comment]
Thanks for the quick response @uriyyo,
Changing from:
```
from pydantic import Field
Page = Page.with_custom_options(
    size=Field(100, ge=1, le=1000),
)
```
To:
```
from fastapi import Query
Page = Page.with_custom_options(
    size=Query(100, ge=1, le=1000),
)
```

Seem to fix the issue.
I recommend adding the change in the docs as a migration guide between the versions!
