### ISSUE TITLE
Cursor Pagination - Invalid cursor value

### ISSUE THREAD

**Issue by Gamattowicz** [uriyyo/fastapi-pagination#1047]
Hi, I tried playing a little with cursor pagination, but whatever I tried I just get this error every time: 
> {
  "detail": "Invalid cursor value"
}

Here is my code snippet for simple endpoint:
```python
import typing
from contextlib import asynccontextmanager

from alchemical.aio import Alchemical
from fastapi import Depends, FastAPI
from fastapi_pagination import add_pagination
from fastapi_pagination.cursor import CursorPage
from fastapi_pagination.ext.sqlalchemy import paginate
from pydantic import BaseModel
from sqlalchemy import Column, Integer, String, select
from sqlalchemy.ext.asyncio import AsyncSession

db = Alchemical("sqlite:///test.db")


class User(db.Model):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)
    name = Column(String)


class UserSchema(BaseModel):
    id: int
    name: str


async def get_session() -> typing.AsyncIterator[AsyncSession]:
    async with db.Session() as session:
        yield session


@asynccontextmanager
async def lifespan(_app: FastAPI):
    await db.create_all()
    async with db.begin() as session:
        session.add_all([User(name=str(i)) for i in range(50)])
    yield
    await db.drop_all()


app = FastAPI(lifespan=lifespan)
add_pagination(app)


@app.get("/users", response_model=CursorPage[UserSchema])
async def get_users(session: AsyncSession = Depends(get_session)):
    return paginate(session, select(User).order_by(User.id))
```

**Comment by uriyyo** [comment]
Hi @Gamattowicz,

What version of fastapi-pagination are you using?

I can run you snippet without any error (you missed await in one place):
```py
import typing
from contextlib import asynccontextmanager

from alchemical.aio import Alchemical
from fastapi import Depends, FastAPI
from pydantic import BaseModel
from sqlalchemy import Column, Integer, String, select
from sqlalchemy.ext.asyncio import AsyncSession

from fastapi_pagination import add_pagination
from fastapi_pagination.cursor import CursorPage
from fastapi_pagination.ext.sqlalchemy import paginate

db = Alchemical("sqlite:///test.db")


class User(db.Model):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)
    name = Column(String)


class UserSchema(BaseModel):
    id: int
    name: str


async def get_session() -> typing.AsyncIterator[AsyncSession]:
    async with db.Session() as session:
        yield session


@asynccontextmanager
async def lifespan(_app: FastAPI):
    await db.create_all()
    async with db.begin() as session:
        session.add_all([User(name=str(i)) for i in range(50)])
    yield
    await db.drop_all()


app = FastAPI(lifespan=lifespan)
add_pagination(app)


@app.get("/users", response_model=CursorPage[UserSchema])
async def get_users(session: AsyncSession = Depends(get_session)):
    return await paginate(session, select(User).order_by(User.id))


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app)
```
```bash
curl -X 'GET' \
  'http://localhost:8000/users?cursor=Pmk6MTA%253D&size=10' \
  -H 'accept: application/json'
```
```json
{
  "items": [
    {
      "id": 11,
      "name": "10"
    },
    {
      "id": 12,
      "name": "11"
    },
    {
      "id": 13,
      "name": "12"
    },
    {
      "id": 14,
      "name": "13"
    },
    {
      "id": 15,
      "name": "14"
    },
    {
      "id": 16,
      "name": "15"
    },
    {
      "id": 17,
      "name": "16"
    },
    {
      "id": 18,
      "name": "17"
    },
    {
      "id": 19,
      "name": "18"
    },
    {
      "id": 20,
      "name": "19"
    }
  ],
  "total": null,
  "current_page": "Pmk6MTA%3D",
  "current_page_backwards": "PGk6MjE%3D",
  "previous_page": "PGk6MTE%3D",
  "next_page": "Pmk6MjA%3D"
}
```

**Comment by Gamattowicz** [comment]
I still get the same error. I use fastapi-pagination 0.12.17. The python version is 3.12.1.
This is a list all of packages or libraries installed in the virtual environment in which I run applications:

```text
aiosqlite==0.19.0
annotated-types==0.6.0
anyio==4.2.0
click==8.1.7
colorama==0.4.6
databases==0.8.0
fastapi==0.109.0
fastapi-pagination==0.12.17
greenlet==3.0.3
h11==0.14.0
idna==3.6
pydantic==2.5.3
pydantic_core==2.14.6
sniffio==1.3.0
SQLAlchemy==1.4.51
starlette==0.35.1
typing_extensions==4.9.0
uvicorn==0.25.0
```

**Comment by uriyyo** [comment]
What version of `alchemical` are you using?

When I try to run your code snippet with the library versions that you provided I am receiving this error:
```py
Traceback (most recent call last):
  File "/mnt/d/projects/fastapi-pagination/temp.py", line 4, in <module>
    from alchemical.aio import Alchemical
  File "/home/uriyyo/.cache/pypoetry/virtualenvs/fastapi-pagination-qCLVCiBY-py3.11/lib/python3.11/site-packages/alchemical/__init__.py", line 1, in <module>
    from .core import Alchemical, Model  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uriyyo/.cache/pypoetry/virtualenvs/fastapi-pagination-qCLVCiBY-py3.11/lib/python3.11/site-packages/alchemical/core.py", line 6, in <module>
    from sqlalchemy.orm import DeclarativeBase, sessionmaker
ImportError: cannot import name 'DeclarativeBase' from 'sqlalchemy.orm' (/home/uriyyo/.cache/pypoetry/virtualenvs/fastapi-pagination-qCLVCiBY-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/__init__.py
```

**Comment by Gamattowicz** [comment]
My bad. I use Alchemical 1.0.1. 
And its updated list (with added Alchemical and SQLAlchemy versions):

```text
aiosqlite==0.19.0
alchemical==1.0.1
annotated-types==0.6.0
anyio==4.2.0
click==8.1.7
colorama==0.4.6
databases==0.8.0
fastapi==0.109.0
fastapi-pagination==0.12.17
greenlet==3.0.3
h11==0.14.0
idna==3.6
pydantic==2.5.3
pydantic_core==2.14.6
sniffio==1.3.0
SQLAlchemy==2.0.27
starlette==0.35.1
typing_extensions==4.9.0
uvicorn==0.25.0

```

**Comment by Gamattowicz** [comment]
Sure.
This is `curl`:

```text
curl -X 'GET' \
  'http://127.0.0.1:8000/users?cursor=5&size=10' \
  -H 'accept: application/json'
  ```
  
  And this is `Response body` with 400 `status code`:
  ```text
  {
  "detail": "Invalid cursor value"
}
```

**Comment by uriyyo** [comment]
It's not the correct cursor value, you should use the value that the endpoint will gonna return to you. 

First, you need to call endpoint:
```bash
curl -X 'GET' \
  'http://localhost:8000/users?size=50' \
  -H 'accept: application/json'
```

In response you will see cursor values:
```py
{
  "items": [
    {
      "id": 51,
      "name": "0"
    },
    ...
    {
      "id": 100,
      "name": "49"
    }
  ],
  "total": null,
  "current_page": "Pg%3D%3D",
  "current_page_backwards": "PGk6MTE%3D",
  "previous_page": null,
  "next_page": "Pmk6MTA%3D"
}
```

Now you can take `next_page` value and use it as the cursor value when you call the endpoint:
```bash
curl -X 'GET' \
  'http://localhost:8000/users?cursor=Pmk6MTA%3D&size=10' \
  -H 'accept: application/json'
``` 

And then response will look like this:
```py
{
  "items": [
    {
      "id": 11,
      "name": "10"
    },
    ...
    {
      "id": 20,
      "name": "19"
    }
  ],
  "total": null,
  "current_page": "Pmk6MTA%3D",
  "current_page_backwards": "PGk6MjE%3D",
  "previous_page": "PGk6MTE%3D",
  "next_page": "Pmk6MjA%3D"
}
```

You can take a look at the example - https://github.com/uriyyo/fastapi-pagination/blob/main/examples/cursor/app.py

**Comment by Gamattowicz** [comment]
I had to install also `sqlakeyset`, but now it's working. Thank you for your help and patience.

**Comment by uriyyo** [comment]
Great, happy to hear that!
