### ISSUE TITLE
Version `0.12.18` breaks pydantic resolution

### ISSUE THREAD

**Issue by MoritzWeber0** [uriyyo/fastapi-pagination#1068]
In Version `0.12.18`, I get the following stacktrace in my application. It works fine when using version `0.12.17`. 

```py
Traceback (most recent call last):
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 677, in _resolve_forward_ref
    obj = _typing_extra.eval_type_backport(obj, globalns=self._types_namespace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_typing_extra.py", line 240, in eval_type_backport
    return typing._eval_type(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/typing.py", line 381, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/typing.py", line 891, in _evaluate
    eval(self.__forward_code__, globalns, localns),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'ProjectUserAssociation' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/capellacollab/__main__.py", line 39, in <module>                    github/capella-collab-manager/backend/.venv/lib/python3.11/site-packag
    from capellacollab.routes import router
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/capellacollab/routes.py", line 16, in <module>                      ^^^
    from capellacollab.projects import routes as projects_routes
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/capellacollab/projects/routes.py", line 17, in <module>
    from capellacollab.projects.events import routes as projects_events_routes
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/capellacollab/projects/events/routes.py", line 15, in <module>      _disconnect, send_no_error)
    from . import crud
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/capellacollab/projects/events/crud.py", line 17, in <module>
    ) -> fastapi_pagination.Page[DatabaseUserHistoryEvent]:
         ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/main.py", line 687, in __class_getitem__
    submodel = _generics.create_generic_submodel(model_name, origin, args, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generics.py", line 138, in create_generic_submodel
    created_model = meta(
                    ^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 199, in __new__
    super(cls, cls).__pydantic_init_subclass__(**kwargs)  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/fastapi_pagination/bases.py", line 161, in __pydantic_init_subclass__
    cls.model_rebuild(force=True)
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/main.py", line 476, in model_rebuild
    return _model_construction.complete_model_class(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 517, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/main.py", line 584, in __get_pydantic_core_schema__
    return __handler(__source)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 499, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 737, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 759, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 572, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 572, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 923, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1045, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1747, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1728, in inner_handler
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 737, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 764, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 847, in match_type
    return self._match_generic_type(obj, origin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 887, in _match_generic_type
    return self._sequence_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1390, in _sequence_schema
    list_schema = core_schema.list_schema(self.generate_schema(item_type))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 499, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 737, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 764, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 838, in match_type
    return self._dataclass_schema(obj, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1487, in _dataclass_schema
    args = sorted(
           ^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1488, in <genexpr>
    (self._generate_dc_field_schema(k, v, decorators) for k, v in fields.items()),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 940, in _generate_dc_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1045, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1747, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1728, in inner_handler
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 737, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 764, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 838, in match_type
    return self._dataclass_schema(obj, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1487, in _dataclass_schema
    args = sorted(
           ^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1488, in <genexpr>
    (self._generate_dc_field_schema(k, v, decorators) for k, v in fields.items()),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 940, in _generate_dc_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1045, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1747, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1829, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_std_types_schema.py", line 316, in __get_pydantic_core_schema__
    items_schema = handler.generate_schema(self.item_source_type)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 96, in generate_schema
    return self._generate_schema.generate_schema(__source_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 499, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 737, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 754, in _generate_schema_inner
    return self.generate_schema(self._resolve_forward_ref(obj))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 679, in _resolve_forward_ref
    raise PydanticUndefinedAnnotation.from_name_error(e) from e
pydantic.errors.PydanticUndefinedAnnotation: name 'ProjectUserAssociation' is not defined

For further information visit https://errors.pydantic.dev/2.6/u/undefined-annotation
```

The relevant code line is available here: https://github.com/DSD-DBS/capella-collab-manager/blob/79735fb2f8702af5645a4174b4020d9ae12ae6c3/backend/capellacollab/projects/events/crud.py#L14

If the issue is not known and you need a minimal reproducible setup, let me know and I'll try to set it up. 

`pip list`:
```
aiohttp                   3.8.5
aioresponses              0.7.4
aiosignal                 1.3.1
alembic                   1.13.1
annotated-types           0.5.0
anyio                     3.7.1
appdirs                   1.4.4
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
astroid                   3.0.3
async-timeout             4.0.3
attrs                     23.1.0
black                     23.7.0
cachetools                5.3.1
capellacollab-backend     2.25.2.dev48+g12069f646.d20240201 /Users/moritzweber/Projects/github/capella-collab-manager/backend
capellambse               0.5.36
certifi                   2023.7.22
cffi                      1.15.1
charset-normalizer        3.2.0
click                     8.1.6
coverage                  7.2.7
croniter                  2.0.1
cryptography              41.0.3
dataclasses-json          0.5.14
deepdiff                  6.3.1
deprecation               2.1.0
dill                      0.3.7
docker                    6.1.3
ecdsa                     0.18.0
fastapi                   0.103.1
fastapi-pagination        0.12.18
frozenlist                1.4.0
google-auth               2.22.0
h11                       0.14.0
htmlmin                   0.1.12
httpcore                  0.17.3
httptools                 0.6.0
httpx                     0.24.1
idna                      3.4
iniconfig                 2.0.0
isort                     5.12.0
Jinja2                    3.1.2
json-schema-for-humans    0.46
jsonschema                4.19.0
jsonschema-specifications 2023.7.1
kubernetes                27.2.0
lazy-object-proxy         1.9.0
lxml                      4.9.3
Mako                      1.2.4
markdown2                 2.4.10
MarkupSafe                2.1.3
marshmallow               3.20.1
mccabe                    0.7.0
msal                      1.23.0
multidict                 6.0.4
mypy                      1.5.0
mypy-extensions           1.0.0
oauthlib                  3.2.2
openshift                 0.13.2
ordered-set               4.1.0
packaging                 23.1
pathspec                  0.11.2
Pillow                    10.0.1
pip                       23.3.2
platformdirs              3.10.0
pluggy                    1.2.0
prometheus-client         0.12.0
psycopg2-binary           2.9.6
pyasn1                    0.5.0
pyasn1-modules            0.3.0
pycparser                 2.21
pydantic                  2.6.3
pydantic_core             2.16.3
Pygments                  2.16.1
PyJWT                     2.8.0
pylint                    3.0.3
pytest                    7.4.0
pytest-cov                4.1.0
python-dateutil           2.8.2
python-dotenv             1.0.0
python-jose               3.3.0
python-multipart          0.0.6
python-slugify            8.0.1
python-string-utils       1.0.0
pytz                      2023.3.post1
PyYAML                    6.0.1
referencing               0.30.2
requests                  2.31.0
requests-oauthlib         1.3.1
responses                 0.23.3
rpds-py                   0.9.2
rsa                       4.9
setuptools                68.0.0
six                       1.16.0
sniffio                   1.3.0
SQLAlchemy                2.0.19
starlette                 0.27.0
starlette-prometheus      0.9.0
svgwrite                  1.4.3
testcontainers            3.7.1
text-unidecode            1.3
tomlkit                   0.12.1
typer                     0.9.0
types-PyYAML              6.0.12.11
typing_extensions         4.10.0
typing-inspect            0.9.0
Unidecode                 1.3.6
urllib3                   1.26.16
uvicorn                   0.23.2
uvloop                    0.17.0
watchfiles                0.19.0
websocket-client          1.6.1
websockets                11.0.3
wrapt                     1.15.0
yarl                      1.9.2
```

**Comment by uriyyo** [comment]
Hi @MoritzWeber0,

Could you please provide min steps to reproduce this issue?

**Comment by uriyyo** [comment]
Hi @MoritzWeber0,

This issue should be fixed in version `0.12.19`. Could you please verify it on your side?

**Comment by MoritzWeber0** [comment]
> Hi @MoritzWeber0,
> 
> This issue should be fixed in version `0.12.19`. Could you please verify it on your side?

Thanks you for the quick fix! I'm still waiting for the pipeline to see if everything goes through, but the manual tests all look good.

**Comment by MoritzWeber0** [comment]
Pipeline went through. Thanks again 👍

**Comment by MoritzWeber0** [comment]
Fixed with https://github.com/uriyyo/fastapi-pagination/pull/1069

**Comment by uriyyo** [comment]
Great news! Thanks for quick update!
