### ISSUE TITLE
 __init__() missing 1 required positional argument: 'detail' (type=type_error)

### ISSUE THREAD

**Issue by wasuaje** [uriyyo/fastapi-pagination#143]
Hello everyone
I'm receiving this weird error when browsing "/api/invoice" although I followed the guide.
The only thing here is mi response schema has a field represented by another schema

Thanks in advance for the help

fastapi_pagination Version
0.8.1
FastApi Version:
```
FastAPI framework, high performance, easy to learn, fast to code, ready for production"
__version__ = "0.65.2"

```

```
 INFO:     172.20.0.1:52946 - "GET /api/invoice/ HTTP/1.1" 500 Internal Server Error
backend_1       | ERROR:    Exception in ASGI application
backend_1       | Traceback (most recent call last):
backend_1       |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
backend_1       |     result = await app(self.scope, self.receive, self.send)
backend_1       |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
backend_1       |     return await self.app(scope, receive, send)
backend_1       |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
backend_1       |     await super().__call__(scope, receive, send)
backend_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
backend_1       |     await self.middleware_stack(scope, receive, send)
backend_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
backend_1       |     raise exc from None
backend_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
backend_1       |     await self.app(scope, receive, _send)
backend_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
backend_1       |     await self.app(scope, receive, send)
backend_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
backend_1       |     raise exc from None
backend_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
backend_1       |     await self.app(scope, receive, sender)
backend_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
backend_1       |     await route.handle(scope, receive, send)
backend_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
backend_1       |     await self.app(scope, receive, send)
backend_1       |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
backend_1       |     response = await func(request)
backend_1       |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 222, in app
backend_1       |     response_data = await serialize_response(
backend_1       |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 127, in serialize_response
backend_1       |     raise ValidationError(errors, field.type_)
backend_1       | pydantic.error_wrappers.ValidationError: 4 validation errors for Page[InvoiceResponse]
backend_1       | response -> items -> 3 -> invoice_detail -> 0
backend_1       |   __init__() missing 1 required positional argument: 'detail' (type=type_error)
backend_1       | response -> items -> 4 -> invoice_detail -> 0
backend_1       |   __init__() missing 1 required positional argument: 'detail' (type=type_error)
backend_1       | response -> items -> 4 -> invoice_detail -> 1
backend_1       |   __init__() missing 1 required positional argument: 'detail' (type=type_error)
backend_1       | response -> items -> 4 -> invoice_detail -> 2
backend_1       |   __init__() missing 1 required positional argument: 'detail' (type=type_error)

```

Model:
```
class Invoice(Base):
    __tablename__ = "app_invoice"

    id = Column(Integer, primary_key=True, index=True)
    date = Column(Date)
    invoice = Column(String(20), nullable=True)
    order = Column(String(20), nullable=True)
    payment_nro = Column(String(20), nullable=True)
    payment_method = Column(String(20), nullable=True)
    created_on = Column(DateTime, default=datetime.datetime.now())
    contact_id = Column(Integer, ForeignKey("app_contact.id"))
    profesional_id = Column(Integer, ForeignKey("app_profesional.id"))
    client = relationship("Client", back_populates="invoice")
    invoice_detail = relationship("InvoiceDetail", back_populates="invoice")
    profesional = relationship("Profesional", back_populates="invoice")
    
    @hybrid_property
    def total(self):
        return func.sum(self.invoice_detail.total)
```
Schema:

```
class InvoiceResponse(BaseModel):
    id: int
    date: datetime.date
    invoice: str
    order: Optional[str]
    payment_nro: Optional[str]
    payment_method: Optional[str]
    profesional: ProfesionalResponse
    client: ClientResponse    
    created_on: datetime.datetime
    total: Optional[float] = 0.00
    invoice_detail: List[InvoiceDetailResponse]

    class Config:
        orm_mode = True

```
Linked Schema:

```
class InvoiceDetailResponse(Invoice):
    qtty: int
    price: float
    invoice_id: int
    product: ProductResponse
    total: Optional[float] = 0.00

    class Config:
        orm_mode = True

    def __init__(self, detail: InvoiceDetail, **data):
        super().__init__(total=InvoiceDetail.qtty*InvoiceDetail.price, **data)

```

Router:

```
@router.get("/api/invoice/", response_model=Page[InvoiceResponse], tags=["Invoice"])
def list_invoice(skip: int = 0, limit: int = 100,
                 db: Session = Depends(get_db),
                 current_user: User = Depends(get_current_active_user)):
    invoice = get_invoicees(db, skip=skip, limit=limit)
    # return invoice
    return paginate(invoice)

```

**Comment by wasuaje** [comment]
I'm afraid and happy I could find the error myself
In here

Linked Schema:

```
class InvoiceDetailResponse(Invoice):
    qtty: int
    price: float
    invoice_id: int
    product: ProductResponse
    total: Optional[float] = 0.00

    class Config:
        orm_mode = True

    def __init__(self, detail: InvoiceDetail, **data):
        super().__init__(total=InvoiceDetail.qtty*InvoiceDetail.price, **data)
```

this line was unused as It didn´t work

```
    def __init__(self, detail: InvoiceDetail, **data):
        super().__init__(total=InvoiceDetail.qtty*InvoiceDetail.price, **data)

```
Removing this made it work
