### ISSUE TITLE
Increasing limit value

### ISSUE THREAD

**Issue by yovizzle** [uriyyo/fastapi-pagination#21]
Hey there, is it possible to increase the limit value? I tried to define `pagination_params` as below (informed by #17), but had no luck. What is the correct way to do it?

Thanks! 

```
from fastapi_pagination import Page, using_params
from fastapi_pagination.params import LimitOffsetPaginationParams


@dataclass
class CustomPaginationPrams:
    page: int = 0
    size: int = 10000

    def to_limit_offset(self) -> LimitOffsetPaginationParams:
        return LimitOffsetPaginationParams(
            limit=self.size,
            offset=self.size * self.page,
        )


pagination_params = using_params(CustomPaginationPrams)
```

Error message received:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 190, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 189, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 135, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/main.py", line 64, in get_studies
    return paginate(studies)
  File "/usr/local/lib/python3.7/site-packages/fastapi_pagination/paginator.py", line 11, in paginate
    limit_offset_params = params.to_limit_offset()
  File "/app/main.py", line 45, in to_limit_offset
    offset=self.size * self.page,
  File "<string>", line 5, in __init__
  File "pydantic/dataclasses.py", line 107, in pydantic.dataclasses._process_class._pydantic_post_init
pydantic.error_wrappers.ValidationError: 1 validation error for LimitOffsetPaginationParams
limit
  ensure this value is less than or equal to 100 (type=value_error.number.not_le; limit_value=100)```

**Comment by yovizzle** [comment]
Sorry, I didn't see #17. Closing this now.  Thank you!

**Comment by uriyyo** [comment]
Hi, this is a bug. I am preparing new version which will fix this issue.

**Comment by uriyyo** [comment]
Hi @yovizzle, version `0.6.0` is released, to solve your problem, please use code like this:
```python
from typing import TypeVar, Generic

from fastapi import Query

from fastapi_pagination.default import Page as BasePage, Params as BaseParams

T = TypeVar("T")


class Params(BaseParams):
    size: int = 10000


class Page(BasePage[T], Generic[T]):
    __params_type__ = Params
```

**Comment by uriyyo** [comment]
Hi @yovizzle, I am closing this issue, in case when it's not working as you expected, please reopen this PR)
