### ISSUE TITLE
Error using fastapi middleware and fastapi-pagination together

### ISSUE THREAD

**Issue by anye88** [uriyyo/fastapi-pagination#309]
## error
```
Traceback (most recent call last):
  File "/opt/environment/api/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/environment/api/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/environment/api/lib/python3.9/site-packages/fastapi/applications.py", line 212, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/python39/lib/python3.9/contextlib.py", line 651, in __aexit__
    raise exc_details[1]
  File "/usr/local/python39/lib/python3.9/contextlib.py", line 193, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/opt/environment/api/lib/python3.9/site-packages/fastapi_pagination/api.py", line 104, in _set_request_response
    yield
  File "/usr/local/python39/lib/python3.9/contextlib.py", line 634, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/usr/local/python39/lib/python3.9/contextlib.py", line 182, in __aexit__
    await self.gen.__anext__()
  File "/opt/environment/api/lib/python3.9/site-packages/fastapi_pagination/api.py", line 83, in _set_page_type
    yield
  File "/usr/local/python39/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/opt/environment/api/lib/python3.9/site-packages/fastapi_pagination/api.py", line 71, in _reset_ctx
    var.reset(token)
ValueError: <Token var=<ContextVar name='page_type' default=<class 'fastapi_pagination.default.Page'> at 0x7f72ec168db0> at 0x7f72ec14f940> was created in a different Context
```
## test code

```python
from typing import Any

import uvicorn
from faker import Faker
from fastapi import FastAPI
from pydantic import BaseModel
from tortoise import Model
from tortoise.contrib.fastapi import register_tortoise
from tortoise.fields import IntField, TextField

from fastapi_pagination import LimitOffsetPage, Page, add_pagination
from fastapi_pagination.ext.tortoise import paginate

import time

from fastapi import Request

faker = Faker()


class User(Model):
    id = IntField(pk=True)
    name = TextField(null=False)
    email = TextField(null=False)


class UserIn(BaseModel):
    name: str
    email: str


class UserOut(UserIn):
    id: int

    class Config:
        orm_mode = True


app = FastAPI()

register_tortoise(
    app,
    db_url="sqlite://:memory:",
    modules={"models": [__name__]},
    generate_schemas=True,
)


@app.on_event("startup")
async def on_startup() -> None:
    for _ in range(100):
        await User.create(
            name=faker.name(),
            email=faker.email(),
        )


@app.post("/users", response_model=UserOut)
async def create_user(user_in: UserIn) -> Any:
    return await User.create(**user_in.dict())


@app.get("/users/default", response_model=Page[UserOut])
@app.get("/users/limit-offset", response_model=LimitOffsetPage[UserOut])
async def get_users() -> Any:
    return await paginate(User)


add_pagination(app)

@app.middleware("http")
async def add_process_time_header(request: Request, call_next):
    start_time = time.time()
    response = await call_next(request)
    process_time = time.time() - start_time
    response.headers["X-Process-Time"] = str(process_time)
    return response

if __name__ == "__main__":
    uvicorn.run("pagination_tortoise:app")

```

**Comment by uriyyo** [comment]
Hi @anye88,

Could you please provide versions of the packages and python that you are using?

I can't reproduce this issue with latest `fastapi-pagination` version and python `3.9.7` version.

**Comment by anye88** [comment]
```
Python 3.9.6
fastapi==0.73.0
fastapi-pagination==0.9.2
```

**Comment by uriyyo** [comment]
Looks like it's some `fastapi` issue. I can't reproduce it with latest `fastapi` version.

**Comment by uriyyo** [comment]
@anye88 This issue has been fixed. Please, use `0.9.3` version.
