### ISSUE TITLE
Linked pagination does not work with APIRouter

### ISSUE THREAD

**Issue by TamiasSibiricus** [uriyyo/fastapi-pagination#333]
Hi

**Problem:**
In context of usage Links inside pagination i have found sample where i can customise links output #321 This code works well until i try to apply pagination through APIRouter. FastAPI respond with 500 error with message in log "request context var must be set". It does not work even i use linked Page  realisation from module without customisations

**Source sample code:**

```python
from typing import TypeVar, Optional, Any, Generic

from fastapi import FastAPI, APIRouter, Depends
from pydantic import BaseModel, validator, Field, root_validator

from fastapi_pagination import paginate, Params
from fastapi_pagination.links import Page as BasePage

app = FastAPI(root_path="/services")


class User(BaseModel):
    name: str
    surname: str


T = TypeVar("T")


class LinkDescription(BaseModel):
    href: str = Field(..., example="/users")
    method: str = Field(..., example="GET")


class Links(BaseModel):
    first: LinkDescription
    last: LinkDescription
    self: LinkDescription
    next: Optional[LinkDescription]
    prev: Optional[LinkDescription]
    add: LinkDescription

    @root_validator(pre=True)
    def __root_validator__(cls, values: dict[str, Any]) -> dict[str, Any]:
        return {"add": {"href": "", "method": "POST"}, **values}

    @validator("first", "last", "self", "next", "prev", pre=True)
    def __field_validator__(cls, v: Any) -> Any:
        if isinstance(v, str):
            return {"href": v, "method": "GET"}

        return v

    @validator("add")
    def __validate_add__(cls, v: Any, values: dict[str, Any]) -> Any:
        v.href, *_ = values["first"].href.split("?")
        return v


class Page(BasePage[T], Generic[T]):
    links: Links


users_router = APIRouter()

@users_router.get('/', response_model=Page[User])
async def get_users(params: Params = Depends()):
    users = [
        User(name='Yurii', surname='Karabas'),
        User(name='Yurii', surname='Karabas'),
        User(name='Yurii', surname='Karabas'),
    ]
    return paginate(users, params)


@app.on_event("startup")
async def startup():
    app.include_router(users_router, prefix="/users", tags=["user"])


if __name__ == '__main__':
    import uvicorn

    uvicorn.run(app)
```

**Expected result:**

```json
{
  "items": [
    {
      "name": "Yurii",
      "surname": "Karabas"
    },
    {
      "name": "Yurii",
      "surname": "Karabas"
    },
    {
      "name": "Yurii",
      "surname": "Karabas"
    }
  ],
  "total": 3,
  "page": 1,
  "size": 50,
  "links": {
    "first": {
      "href": "/users?page=1",
      "method": "GET"
    },
    "last": {
      "href": "/users?page=1",
      "method": "GET"
    },
    "self": {
      "href": "/users",
      "method": "GET",
    },
    "next": null,
    "prev": null,
    "add": {
        "href": "/users",
        "method": "POST",
    }
  }
}
```

**Fact result in log:**

```python
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/debug.py", line 106, in __call__
    raise exc from None
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/debug.py", line 103, in __call__
    await self.app(scope, receive, inner_send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
    response_data = await serialize_response(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 128, in serialize_response
    value, errors_ = field.validate(response_content, {}, loc=("response",))
  File "pydantic/fields.py", line 857, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1074, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 1121, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 313, in pydantic.class_validators._generic_validator_basic.lambda12
  File "pydantic/main.py", line 686, in pydantic.main.BaseModel.validate
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1012, in pydantic.main.validate_model
  File "/usr/local/lib/python3.10/site-packages/fastapi_pagination/links/default.py", line 22, in __root_validator__
    value["links"] = create_links(
  File "/usr/local/lib/python3.10/site-packages/fastapi_pagination/links/bases.py", line 39, in create_links
    req = request()
  File "/usr/local/lib/python3.10/site-packages/fastapi_pagination/api.py", line 62, in request
    raise RuntimeError("request context var must be set")
RuntimeError: request context var must be set
```

**Comment by uriyyo** [comment]
Hi @TamiasSibiricus,

You need to call `add_pagination` with `FastAPI` instance after all routers registration:
```py
from typing import TypeVar, Optional, Any, Generic

from fastapi import FastAPI, APIRouter, Depends
from pydantic import BaseModel, validator, Field, root_validator

from fastapi_pagination import paginate, Params, add_pagination
from fastapi_pagination.links import Page as BasePage

app = FastAPI(root_path="/services")


class User(BaseModel):
    name: str
    surname: str


T = TypeVar("T")


class LinkDescription(BaseModel):
    href: str = Field(..., example="/users")
    method: str = Field(..., example="GET")


class Links(BaseModel):
    first: LinkDescription
    last: LinkDescription
    self: LinkDescription
    next: Optional[LinkDescription]
    prev: Optional[LinkDescription]
    add: LinkDescription

    @root_validator(pre=True)
    def __root_validator__(cls, values: dict[str, Any]) -> dict[str, Any]:
        return {"add": {"href": "", "method": "POST"}, **values}

    @validator("first", "last", "self", "next", "prev", pre=True)
    def __field_validator__(cls, v: Any) -> Any:
        if isinstance(v, str):
            return {"href": v, "method": "GET"}

        return v

    @validator("add")
    def __validate_add__(cls, v: Any, values: dict[str, Any]) -> Any:
        v.href, *_ = values["first"].href.split("?")
        return v


class Page(BasePage[T], Generic[T]):
    links: Links


users_router = APIRouter()

@users_router.get('/', response_model=Page[User])
async def get_users(params: Params = Depends()):
    users = [
        User(name='Yurii', surname='Karabas'),
        User(name='Yurii', surname='Karabas'),
        User(name='Yurii', surname='Karabas'),
    ]
    return paginate(users, params)


app.include_router(users_router, prefix="/users", tags=["user"])
add_pagination(app)

if __name__ == '__main__':
    import uvicorn

    uvicorn.run(app)
```

**Comment by TamiasSibiricus** [comment]
Ok. My fault was to call add_paginate outside of startup event where  router additions happens. so it make situation when routes has been added(probably) after pagination apply.
 
So code samples

```python
app = FastAPI()
@app.on_event("startup")
async def startup():
    # Add routes first in event
    app.include_router(projects_router, prefix="/projects", tags=["project"])
    # Apply pagination for any registered route previously in event too 
    add_pagination(app)
```

or 

```python
app = FastAPI()
@app.on_event("startup")
async def startup():
    #do something here
    pass
# Add routes first not in event
app.include_router(projects_router, prefix="/projects", tags=["project"])
# Apply pagination for any registered route previously outside event too
add_pagination(app)
```

Both examples work like a charm, but all of them require routes registration before and on same action level where add_pagination called.
