### ISSUE TITLE
'Select' object has no attribute 'to_raw_params'

### ISSUE THREAD

**Issue by chichi13** [uriyyo/fastapi-pagination#349]
I've just tried this package, according to the example and the doc I've tried this :

```python3
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select

from app.models.user import User

router = APIRouter(prefix="/admin")

@router.get("/users", response_model=Page[UserSchema], name="Get all users")
async def get_users(
    db: AsyncSession = Depends(get_db),
):
    users = select(User)

    return await paginate(db, users)
```

Where `User` is : 

```python3
class User(Base, BaseFeaturesMixin):
    __tablename__ = "users"

    username = Column(String, unique=True, index=True, nullable=False)
    email = Column(String, unique=True, index=True, nullable=False)
    password = Column(String, nullable=False)
    is_active = Column(Boolean, default=True)
```

This `paginate(db, users)` seems to be the problem. I get the following error : 

<details>
  <summary>Traceback</summary>
    
  ```bash
Traceback (most recent call last):
  File "/Users/antoine/Documents/Perso/fastapi-app-template/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/antoine/Documents/Perso/fastapi-app-template/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/antoine/Documents/Perso/fastapi-app-template/venv/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/antoine/Documents/Perso/fastapi-app-template/venv/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/antoine/Documents/Perso/fastapi-app-template/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/antoine/Documents/Perso/fastapi-app-template/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/antoine/Documents/Perso/fastapi-app-template/venv/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/Users/antoine/Documents/Perso/fastapi-app-template/venv/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/Users/antoine/Documents/Perso/fastapi-app-template/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/antoine/Documents/Perso/fastapi-app-template/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/antoine/Documents/Perso/fastapi-app-template/venv/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/Users/antoine/Documents/Perso/fastapi-app-template/venv/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/Users/antoine/Documents/Perso/fastapi-app-template/venv/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/Users/antoine/Documents/Perso/fastapi-app-template/venv/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/Users/antoine/Documents/Perso/fastapi-app-template/venv/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/antoine/Documents/Perso/fastapi-app-template/./app/api/endpoints/admin.py", line 26, in get_users
    return await paginate(db, users)
  File "/Users/antoine/Documents/Perso/fastapi-app-template/venv/lib/python3.10/site-packages/fastapi_pagination/paginator.py", line 15, in paginate
    raw_params = params.to_raw_params()
AttributeError: 'Select' object has no attribute 'to_raw_params'
  ```
  
</details>

I'm using : 
- FastAPI : 0.79.0
- asyncpg : 0.26.0
- SQLAlchemy : 1.4.39

Do I do something wrong ?

**Comment by uriyyo** [comment]
Hi @chichi13,

You need to import `paginate` from `fastapi_pagination.ext. async_sqlalchemy`:
```py
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from fastapi_pagination.ext. async_sqlalchemy import paginate

from app.models.user import User

router = APIRouter(prefix="/admin")

@router.get("/users", response_model=Page[UserSchema], name="Get all users")
async def get_users(
    db: AsyncSession = Depends(get_db),
):
    users = select(User)

    return await paginate(db, users)
```

**Comment by chichi13** [comment]
Indeed, I missed that, thanks !
