### ISSUE TITLE
async_sqlalchemy : bug on the paginate() function 

### ISSUE THREAD

**Issue by rerouj** [uriyyo/fastapi-pagination#437]
When using the paginate() function of the async_sqlalchemy extension, the following error is raising :

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  ...
  File "/Users/r/Library/Caches/pypoetry/virtualenvs/app-v2-F6JHflVe-py3.9/lib/python3.9/site-packages/fastapi_pagination/ext/async_sqlalchemy.py", line 26, in paginate
    return create_page(unwrap_scalars(items.unique().all()), total, params)
  File "/Users/r/Library/Caches/pypoetry/virtualenvs/app-v2-F6JHflVe-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1111, in all
    return self._allrows()
  File "/Users/rdiaz/Library/Caches/pypoetry/virtualenvs/app-v2-F6JHflVe-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 410, in _allrows
    rows = [
  File "/Users/r/Library/Caches/pypoetry/virtualenvs/app-v2-F6JHflVe-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 419, in <listcomp>
    if sig_row not in uniques and not uniques.add(sig_row)
TypeError: unhashable type: 'list'
```

I dont know what the error is precisely pointing, but I've founded that the problem is coming from the unique() method used on the session request response. My model is a bit complexe but I think that my datas are pretty clean, so I didn't have troubleshooted the issue any further. I suppose that the problem is coming from a specific model that contains JSONB arrays and  String Arrays columns. When the function is used with a more simple model, the function is working well. Anyway, my solution for the moment, is to remove the unique() method from the paginate function.

Is the problem coming from the sqlalchemy library ? I think this could be posted as an issue. Sorry if it's not the case.

**Comment by dmitrysleptsov** [comment]
Hi, 
Stumbled across your question. I think, this might be the reason of your error https://groups.google.com/g/sqlalchemy/c/FHuCN-X9L8A

**Comment by uriyyo** [comment]
Hi @rerouj,

New version `0.11.1` has been released. Now it's possible to pass `unique` param to `paginate` function:
```py
def get_users(db: Session = Depends(get_db)) -> Any:
    return paginate(select(User), unique=False)
```

I hope it should solve your issue.

**Comment by uriyyo** [comment]
I am closing this issue. @rerouj If you still have issues, please, reopen this issue or create a new one.
