### ISSUE TITLE
TypeError("'ObjectId' object is not iterable")

### ISSUE THREAD

**Issue by Bobspadger** [uriyyo/fastapi-pagination#724]
Hi All

I'm trying to use this library to paginate data from a mongodb database using Motor.

I can get the `paginate()` query to work, and this returns the data from MongoDB/Motor - all good.

My issue comes when I try to then return this via fastAPI return_model and I get the following trace:

```python
Traceback (most recent call last):
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/fastapi/encoders.py", line 152, in jsonable_encoder
    data = dict(obj)
           ^^^^^^^^^
TypeError: 'ObjectId' object is not iterable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/fastapi/encoders.py", line 157, in jsonable_encoder
    data = vars(obj)
           ^^^^^^^^^
TypeError: vars() argument must have __dict__ attribute
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 284, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 259, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 146, in serialize_response
    return jsonable_encoder(
           ^^^^^^^^^^^^^^^^^
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/fastapi/encoders.py", line 66, in jsonable_encoder
    return jsonable_encoder(
           ^^^^^^^^^^^^^^^^^
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/fastapi/encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
                    ^^^^^^^^^^^^^^^^^
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/fastapi/encoders.py", line 131, in jsonable_encoder
    jsonable_encoder(
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/fastapi/encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
                    ^^^^^^^^^^^^^^^^^
  File "/Users/myuser/GIT/fm_webCrawler/.venv/lib/python3.11/site-packages/fastapi/encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors) from e
ValueError: [TypeError("'ObjectId' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
```

I have the following setup to serialise the `ObjectId` to a string and can prove this works by just returning a `List[MyModel]` via fast api.

```python

class PyObjectId(ObjectId):
    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        if not ObjectId.is_valid(v):
            raise ValueError("Invalid objectid")
        return ObjectId(v)

    @classmethod
    def __modify_schema__(cls, field_schema):
        field_schema.update(type="string")






class Result(BaseModel):
    name: Optional[str]
    videolinks: Optional[List] = Field(default_factory=list)
    longdesc: Optional[str]
    highlights: Optional[List] = Field(default_factory=list)
    spec: Optional[List] = Field(default_factory=list)

    class Config:
        allow_population_by_field_name = True
        arbitrary_types_allowed = True
        json_encoders = {ObjectId: str}

class AMSStandardProduct(BaseModel):
    id: PyObjectId = Field(default_factory=PyObjectId, alias="_id")
    mpn: Optional[str]
    status: str = 'NEW'  # Set to enum when done.
    supplier: str
    url: Optional[str]
    result: Optional[Result]

    class Config:
        allow_population_by_field_name = True
        arbitrary_types_allowed = True
        json_encoders = {ObjectId: str}


@app.get(
    "/", response_description="List all products", response_model=Page[AMSStandardProduct]
)
async def list_products():
    products = await paginate(collection=db['supplier'])
    return products


@app.get("/all", response_model=List[AMSStandardProduct])
async def list_all_products():
    products = await db['supplier'].find().to_list(10)
    return products
```

It appears to be around the fact that when my model is no longer the top level, the serialiser fails.

Does anyone have any good examples of this pattern working with Mongo and Motor.

I'm happy to write the examples into the docs etc once I find the answer out :)

**Comment by uriyyo** [comment]
Hi @Bobspadger,

I guess you need to update `json_encoders` for `Page` class:
```py
Page.__config__.json_encoders = {ObjectId: str}
```

**Comment by Bobspadger** [comment]
Thanks - that is fantastic and it fixed it.

What is the best way for me to provide an example in the docs?

**Comment by Bobspadger** [comment]
As an update to this, removing the `PyObjectId` and just setting the standard model to use the following:

```python
class AMSStandardProduct(BaseModel):
    # id: PyObjectId = Field(default_factory=PyObjectId, alias="_id")
    id: str = Field(alias="_id")
    sku: str
    mpn: Optional[str]
    status: str = 'NEW'  # Set to enum when done.
    supplier: str
    url: Optional[str]
    result: Optional[Result]

    @validator('id', pre=True, allow_reuse=True)
    def validate_id(value):
        return str(value)
    class Config:
        allow_population_by_field_name = True
        # arbitrary_types_allowed = True
        # json_encoders = {ObjectId: str}
```

And it all now serialises happily through the `Page` object without having to monkey patch in the serialiser.

**Comment by uriyyo** [comment]
> What is the best way for me to provide an example in the docs?

I guess the best way will be to add `Examples` sections to docs.

**Comment by uriyyo** [comment]
@Bobspadger I am closing this issue. I am happy if you will open PR with fix in docs.
